"""Change account_number to Integer

Revision ID: b52d4738d4de
Revises: 
Create Date: 2024-11-04 15:10:24.971601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52d4738d4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.alter_column('reason_called',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('postcode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('postcode',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('call', schema=None) as batch_op:
        batch_op.alter_column('reason_called',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
